import { KeyMapEntry } from '../../types';

// Avro QWERTY display keymap with phonetic hints
export const AVRO_KEYMAP: Record<string, KeyMapEntry> = {
  // Number Row
  Backquote: { code: 'Backquote', key: '`', label: '`', shiftLabel: '~', finger: 'left-pinky', hand: 'left', row: 'number' },
  Digit1: { code: 'Digit1', key: '1', label: '১', shiftLabel: '!', finger: 'left-pinky', hand: 'left', row: 'number' },
  Digit2: { code: 'Digit2', key: '2', label: '২', shiftLabel: '@', finger: 'left-ring', hand: 'left', row: 'number' },
  Digit3: { code: 'Digit3', key: '3', label: '৩', shiftLabel: '#', finger: 'left-middle', hand: 'left', row: 'number' },
  Digit4: { code: 'Digit4', key: '4', label: '৪', shiftLabel: '$', finger: 'left-index', hand: 'left', row: 'number' },
  Digit5: { code: 'Digit5', key: '5', label: '৫', shiftLabel: '%', finger: 'left-index', hand: 'left', row: 'number' },
  Digit6: { code: 'Digit6', key: '6', label: '৬', shiftLabel: '^', finger: 'right-index', hand: 'right', row: 'number' },
  Digit7: { code: 'Digit7', key: '7', label: '৭', shiftLabel: '&', finger: 'right-index', hand: 'right', row: 'number' },
  Digit8: { code: 'Digit8', key: '8', label: '৮', shiftLabel: '*', finger: 'right-middle', hand: 'right', row: 'number' },
  Digit9: { code: 'Digit9', key: '9', label: '৯', shiftLabel: '(', finger: 'right-ring', hand: 'right', row: 'number' },
  Digit0: { code: 'Digit0', key: '0', label: '০', shiftLabel: ')', finger: 'right-pinky', hand: 'right', row: 'number' },
  Minus: { code: 'Minus', key: '-', label: '-', shiftLabel: '_', finger: 'right-pinky', hand: 'right', row: 'number' },
  Equal: { code: 'Equal', key: '=', label: '=', shiftLabel: '+', finger: 'right-pinky', hand: 'right', row: 'number' },

  // Top Row
  KeyQ: { code: 'KeyQ', key: 'q', label: 'q', shiftLabel: 'Q', finger: 'left-pinky', hand: 'left', row: 'top' },
  KeyW: { code: 'KeyW', key: 'w', label: 'w (ও)', shiftLabel: 'W', finger: 'left-ring', hand: 'left', row: 'top' },
  KeyE: { code: 'KeyE', key: 'e', label: 'e (ে/এ)', shiftLabel: 'E', finger: 'left-middle', hand: 'left', row: 'top' },
  KeyR: { code: 'KeyR', key: 'r', label: 'r (র)', shiftLabel: 'R (ড়)', finger: 'left-index', hand: 'left', row: 'top' },
  KeyT: { code: 'KeyT', key: 't', label: 't (ত)', shiftLabel: 'T (ট)', finger: 'left-index', hand: 'left', row: 'top' },
  KeyY: { code: 'KeyY', key: 'y', label: 'y (য়)', shiftLabel: 'Y', finger: 'right-index', hand: 'right', row: 'top' },
  KeyU: { code: 'KeyU', key: 'u', label: 'u (ু/উ)', shiftLabel: 'U (ূ/ঊ)', finger: 'right-index', hand: 'right', row: 'top' },
  KeyI: { code: 'KeyI', key: 'i', label: 'i (ি/ই)', shiftLabel: 'I (ী/ঈ)', finger: 'right-middle', hand: 'right', row: 'top' },
  KeyO: { code: 'KeyO', key: 'o', label: 'o (অ/ও)', shiftLabel: 'O (ঔ)', finger: 'right-ring', hand: 'right', row: 'top' },
  KeyP: { code: 'KeyP', key: 'p', label: 'p (প)', shiftLabel: 'P', finger: 'right-pinky', hand: 'right', row: 'top' },
  BracketLeft: { code: 'BracketLeft', key: '[', label: '[', shiftLabel: '{', finger: 'right-pinky', hand: 'right', row: 'top' },
  BracketRight: { code: 'BracketRight', key: ']', label: ']', shiftLabel: '}', finger: 'right-pinky', hand: 'right', row: 'top' },

  // Home Row
  KeyA: { code: 'KeyA', key: 'a', label: 'a (া/আ)', shiftLabel: 'A', finger: 'left-pinky', hand: 'left', row: 'home' },
  KeyS: { code: 'KeyS', key: 's', label: 's (স)', shiftLabel: 'S (শ)', finger: 'left-ring', hand: 'left', row: 'home' },
  KeyD: { code: 'KeyD', key: 'd', label: 'd (দ)', shiftLabel: 'D (ড)', finger: 'left-middle', hand: 'left', row: 'home' },
  KeyF: { code: 'KeyF', key: 'f', label: 'f (ফ)', shiftLabel: 'F', finger: 'left-index', hand: 'left', row: 'home' },
  KeyG: { code: 'KeyG', key: 'g', label: 'g (গ)', shiftLabel: 'G (ঘ)', finger: 'left-index', hand: 'left', row: 'home' },
  KeyH: { code: 'KeyH', key: 'h', label: 'h (হ)', shiftLabel: 'H (ঃ)', finger: 'right-index', hand: 'right', row: 'home' },
  KeyJ: { code: 'KeyJ', key: 'j', label: 'j (জ)', shiftLabel: 'J (ঝ)', finger: 'right-index', hand: 'right', row: 'home' },
  KeyK: { code: 'KeyK', key: 'k', label: 'k (ক)', shiftLabel: 'K (খ)', finger: 'right-middle', hand: 'right', row: 'home' },
  KeyL: { code: 'KeyL', key: 'l', label: 'l (ল)', shiftLabel: 'L', finger: 'right-ring', hand: 'right', row: 'home' },
  Semicolon: { code: 'Semicolon', key: ';', label: ';', shiftLabel: ':', finger: 'right-pinky', hand: 'right', row: 'home' },
  Quote: { code: 'Quote', key: "'", label: "'", shiftLabel: '"', finger: 'right-pinky', hand: 'right', row: 'home' },

  // Bottom Row
  KeyZ: { code: 'KeyZ', key: 'z', label: 'z (য)', shiftLabel: 'Z (ঝ)', finger: 'left-pinky', hand: 'left', row: 'bottom' },
  KeyX: { code: 'KeyX', key: 'x', label: 'x (ক্স)', shiftLabel: 'X', finger: 'left-ring', hand: 'left', row: 'bottom' },
  KeyC: { code: 'KeyC', key: 'c', label: 'c (চ)', shiftLabel: 'C (ছ)', finger: 'left-middle', hand: 'left', row: 'bottom' },
  KeyV: { code: 'KeyV', key: 'v', label: 'v (ভ)', shiftLabel: 'V', finger: 'left-index', hand: 'left', row: 'bottom' },
  KeyB: { code: 'KeyB', key: 'b', label: 'b (ব)', shiftLabel: 'B (ভ)', finger: 'left-index', hand: 'left', row: 'bottom' },
  KeyN: { code: 'KeyN', key: 'n', label: 'n (ন)', shiftLabel: 'N (ণ)', finger: 'right-index', hand: 'right', row: 'bottom' },
  KeyM: { code: 'KeyM', key: 'm', label: 'm (ম)', shiftLabel: 'M (ঙ)', finger: 'right-index', hand: 'right', row: 'bottom' },
  Comma: { code: 'Comma', key: ',', label: ',', shiftLabel: '<', finger: 'right-middle', hand: 'right', row: 'bottom' },
  Period: { code: 'Period', key: '.', label: '.', shiftLabel: '।', finger: 'right-ring', hand: 'right', row: 'bottom' },
  Slash: { code: 'Slash', key: '/', label: '/', shiftLabel: '?', finger: 'right-pinky', hand: 'right', row: 'bottom' },

  // Space
  Space: { code: 'Space', key: ' ', label: 'Space', finger: 'thumb', hand: 'right', row: 'space' }
};

// Avro phonetic character to roman keystrokes
export const AVRO_CHAR_TO_KEYSTROKES: Record<string, { key: string; shift: boolean }[]> = {
  'অ': [{ key: 'o', shift: false }],
  'আ': [{ key: 'a', shift: false }],
  'ই': [{ key: 'i', shift: false }],
  'ঈ': [{ key: 'i', shift: true }],
  'উ': [{ key: 'u', shift: false }],
  'ঊ': [{ key: 'u', shift: true }],
  'ঋ': [{ key: 'r', shift: false }, { key: 'r', shift: false }, { key: 'i', shift: false }],
  'এ': [{ key: 'e', shift: false }],
  'ঐ': [{ key: 'o', shift: true }, { key: 'i', shift: true }],
  'ও': [{ key: 'o', shift: false }],
  'ঔ': [{ key: 'o', shift: true }, { key: 'u', shift: true }],

  'া': [{ key: 'a', shift: false }],
  'ি': [{ key: 'i', shift: false }],
  'ী': [{ key: 'i', shift: true }],
  'ু': [{ key: 'u', shift: false }],
  'ূ': [{ key: 'u', shift: true }],
  'ৃ': [{ key: 'r', shift: false }, { key: 'i', shift: false }],
  'ে': [{ key: 'e', shift: false }],
  'ৈ': [{ key: 'o', shift: true }, { key: 'i', shift: false }],
  'ো': [{ key: 'o', shift: false }],
  'ৌ': [{ key: 'o', shift: true }, { key: 'u', shift: false }],

  'ক': [{ key: 'k', shift: false }],
  'খ': [{ key: 'k', shift: false }, { key: 'h', shift: false }],
  'গ': [{ key: 'g', shift: false }],
  'ঘ': [{ key: 'g', shift: false }, { key: 'h', shift: false }],
  'ঙ': [{ key: 'n', shift: true }, { key: 'g', shift: false }],
  'চ': [{ key: 'c', shift: false }],
  'ছ': [{ key: 'c', shift: false }, { key: 'h', shift: false }],
  'জ': [{ key: 'j', shift: false }],
  'ঝ': [{ key: 'j', shift: false }, { key: 'h', shift: false }],
  'ঞ': [{ key: 'n', shift: true }, { key: 'g', shift: true }],
  'ট': [{ key: 't', shift: true }],
  'ঠ': [{ key: 't', shift: true }, { key: 'h', shift: false }],
  'ড': [{ key: 'd', shift: true }],
  'ঢ': [{ key: 'd', shift: true }, { key: 'h', shift: false }],
  'ণ': [{ key: 'n', shift: true }],
  'ত': [{ key: 't', shift: false }],
  'থ': [{ key: 't', shift: false }, { key: 'h', shift: false }],
  'দ': [{ key: 'd', shift: false }],
  'ধ': [{ key: 'd', shift: false }, { key: 'h', shift: false }],
  'ন': [{ key: 'n', shift: false }],
  'প': [{ key: 'p', shift: false }],
  'ফ': [{ key: 'f', shift: false }],
  'ব': [{ key: 'b', shift: false }],
  'ভ': [{ key: 'v', shift: false }],
  'ম': [{ key: 'm', shift: false }],
  'য': [{ key: 'z', shift: false }],
  'র': [{ key: 'r', shift: false }],
  'ল': [{ key: 'l', shift: false }],
  'শ': [{ key: 's', shift: true }],
  'ষ': [{ key: 's', shift: true }, { key: 'h', shift: false }],
  'স': [{ key: 's', shift: false }],
  'হ': [{ key: 'h', shift: false }],
  'ড়': [{ key: 'r', shift: true }],
  'ঢ়': [{ key: 'r', shift: true }, { key: 'h', shift: false }],
  'য়': [{ key: 'y', shift: false }],
  'ৎ': [{ key: 't', shift: false }, { key: '`', shift: false }],
  'ং': [{ key: 'n', shift: false }, { key: 'g', shift: false }],
  'ঃ': [{ key: ';', shift: true }],
  'ঁ': [{ key: '6', shift: true }],
  '।': [{ key: '.', shift: true }],
  ' ': [{ key: ' ', shift: false }],

  // Numbers
  '১': [{ key: '1', shift: false }],
  '২': [{ key: '2', shift: false }],
  '৩': [{ key: '3', shift: false }],
  '৪': [{ key: '4', shift: false }],
  '৫': [{ key: '5', shift: false }],
  '৬': [{ key: '6', shift: false }],
  '৭': [{ key: '7', shift: false }],
  '৮': [{ key: '8', shift: false }],
  '৯': [{ key: '9', shift: false }],
  '০': [{ key: '0', shift: false }],

  // Common Conjuncts
  'ক্ষ': [{ key: 'k', shift: false }, { key: 'k', shift: false }, { key: 'h', shift: false }],
  'জ্ঞ': [{ key: 'j', shift: false }, { key: 'n', shift: false }],
  'ক্ত': [{ key: 'k', shift: false }, { key: 't', shift: false }],
  'ক্র': [{ key: 'k', shift: false }, { key: 'r', shift: false }],
  'ক্ল': [{ key: 'k', shift: false }, { key: 'l', shift: false }],
  'ঙ্ক': [{ key: 'n', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: false }],
  'ঙ্গ': [{ key: 'n', shift: false }, { key: 'g', shift: false }, { key: 'g', shift: false }],
  'চ্চ': [{ key: 'c', shift: false }, { key: 'h', shift: false }, { key: 'c', shift: false }, { key: 'h', shift: false }],
  'চ্ছ': [{ key: 'c', shift: false }, { key: 'h', shift: false }, { key: 'c', shift: false }, { key: 'h', shift: false }, { key: 'h', shift: false }],
  'ঞ্চ': [{ key: 'n', shift: false }, { key: 'c', shift: false }, { key: 'h', shift: false }],
  'ঞ্জ': [{ key: 'n', shift: false }, { key: 'j', shift: false }],
  'ট্ট': [{ key: 't', shift: true }, { key: 't', shift: true }],
  'ট্র': [{ key: 't', shift: true }, { key: 'r', shift: false }],
  'ণ্ট': [{ key: 'n', shift: true }, { key: 't', shift: true }],
  'ণ্ড': [{ key: 'n', shift: true }, { key: 'd', shift: true }],
  'ত্ত': [{ key: 't', shift: false }, { key: 't', shift: false }],
  'ত্র': [{ key: 't', shift: false }, { key: 'r', shift: false }],
  'ত্ব': [{ key: 't', shift: false }, { key: 'w', shift: false }],
  'দ্দ': [{ key: 'd', shift: false }, { key: 'd', shift: false }],
  'দ্ধ': [{ key: 'd', shift: false }, { key: 'd', shift: false }, { key: 'h', shift: false }],
  'দ্ব': [{ key: 'd', shift: false }, { key: 'w', shift: false }],
  'দ্ম': [{ key: 'd', shift: false }, { key: 'm', shift: false }],
  'দ্র': [{ key: 'd', shift: false }, { key: 'r', shift: false }],
  'ন্ত': [{ key: 'n', shift: false }, { key: 't', shift: false }],
  'ন্থ': [{ key: 'n', shift: false }, { key: 't', shift: false }, { key: 'h', shift: false }],
  'ন্দ': [{ key: 'n', shift: false }, { key: 'd', shift: false }],
  'ন্ধ': [{ key: 'n', shift: false }, { key: 'd', shift: false }, { key: 'h', shift: false }],
  'ন্ন': [{ key: 'n', shift: false }, { key: 'n', shift: false }],
  'ন্ম': [{ key: 'n', shift: false }, { key: 'm', shift: false }],
  'প্ত': [{ key: 'p', shift: false }, { key: 't', shift: false }],
  'প্ল': [{ key: 'p', shift: false }, { key: 'l', shift: false }],
  'প্র': [{ key: 'p', shift: false }, { key: 'r', shift: false }],
  'ব্ব': [{ key: 'b', shift: false }, { key: 'b', shift: false }],
  'ব্ল': [{ key: 'b', shift: false }, { key: 'l', shift: false }],
  'ব্র': [{ key: 'b', shift: false }, { key: 'r', shift: false }],
  'ম্প': [{ key: 'm', shift: false }, { key: 'p', shift: false }],
  'ম্ব': [{ key: 'm', shift: false }, { key: 'b', shift: false }],
  'ম্ভ': [{ key: 'm', shift: false }, { key: 'b', shift: false }, { key: 'h', shift: false }],
  'ম্ম': [{ key: 'm', shift: false }, { key: 'm', shift: false }],
  'ম্র': [{ key: 'm', shift: false }, { key: 'r', shift: false }],
  'ল্ল': [{ key: 'l', shift: false }, { key: 'l', shift: false }],
  'শ্চ': [{ key: 's', shift: true }, { key: 'c', shift: false }, { key: 'h', shift: false }],
  'শ্র': [{ key: 's', shift: true }, { key: 'r', shift: false }],
  'শ্ব': [{ key: 's', shift: true }, { key: 'w', shift: false }],
  'ষ্ট': [{ key: 's', shift: true }, { key: 't', shift: true }],
  'ষ্ঠ': [{ key: 's', shift: true }, { key: 't', shift: true }, { key: 'h', shift: false }],
  'ষ্ণ': [{ key: 's', shift: true }, { key: 'n', shift: true }],
  'ষ্প': [{ key: 's', shift: true }, { key: 'p', shift: false }],
  'স্ত': [{ key: 's', shift: false }, { key: 't', shift: false }],
  'স্থ': [{ key: 's', shift: false }, { key: 't', shift: false }, { key: 'h', shift: false }],
  'স্ন': [{ key: 's', shift: false }, { key: 'n', shift: false }],
  'স্প': [{ key: 's', shift: false }, { key: 'p', shift: false }],
  'স্ফ': [{ key: 's', shift: false }, { key: 'p', shift: false }, { key: 'h', shift: false }],
  'স্ব': [{ key: 's', shift: false }, { key: 'w', shift: false }],
  'স্ম': [{ key: 's', shift: false }, { key: 'm', shift: false }],
  'স্র': [{ key: 's', shift: false }, { key: 'r', shift: false }],
  'স্ল': [{ key: 's', shift: false }, { key: 'l', shift: false }],
  'হ্ন': [{ key: 'h', shift: false }, { key: 'n', shift: false }],
  'হ্ম': [{ key: 'h', shift: false }, { key: 'm', shift: false }],
  'হ্ল': [{ key: 'h', shift: false }, { key: 'l', shift: false }],
  'হ্র': [{ key: 'h', shift: false }, { key: 'r', shift: false }]
};
