import { KeyMapEntry } from '../../types';

// Complete standard Bijoy 52 Unicode Keymap
export const BIJOY_KEYMAP: Record<string, KeyMapEntry> = {
  // Number Row
  Backquote: { code: 'Backquote', key: '`', label: '`', shiftLabel: '~', finger: 'left-pinky', hand: 'left', row: 'number' },
  Digit1: { code: 'Digit1', key: '1', label: '১', shiftLabel: '!', finger: 'left-pinky', hand: 'left', row: 'number' },
  Digit2: { code: 'Digit2', key: '2', label: '২', shiftLabel: '@', finger: 'left-ring', hand: 'left', row: 'number' },
  Digit3: { code: 'Digit3', key: '3', label: '৩', shiftLabel: '#', finger: 'left-middle', hand: 'left', row: 'number' },
  Digit4: { code: 'Digit4', key: '4', label: '৪', shiftLabel: '৳', finger: 'left-index', hand: 'left', row: 'number' },
  Digit5: { code: 'Digit5', key: '5', label: '৫', shiftLabel: '%', finger: 'left-index', hand: 'left', row: 'number' },
  Digit6: { code: 'Digit6', key: '6', label: '৬', shiftLabel: '^', finger: 'right-index', hand: 'right', row: 'number' },
  Digit7: { code: 'Digit7', key: '7', label: '৭', shiftLabel: '&', finger: 'right-index', hand: 'right', row: 'number' },
  Digit8: { code: 'Digit8', key: '8', label: '৮', shiftLabel: '*', finger: 'right-middle', hand: 'right', row: 'number' },
  Digit9: { code: 'Digit9', key: '9', label: '৯', shiftLabel: '(', finger: 'right-ring', hand: 'right', row: 'number' },
  Digit0: { code: 'Digit0', key: '0', label: '০', shiftLabel: ')', finger: 'right-pinky', hand: 'right', row: 'number' },
  Minus: { code: 'Minus', key: '-', label: '-', shiftLabel: '_', finger: 'right-pinky', hand: 'right', row: 'number' },
  Equal: { code: 'Equal', key: '=', label: '=', shiftLabel: '+', finger: 'right-pinky', hand: 'right', row: 'number' },

  // Top Row
  KeyQ: { code: 'KeyQ', key: 'q', label: 'ঙ', shiftLabel: 'ং', finger: 'left-pinky', hand: 'left', row: 'top' },
  KeyW: { code: 'KeyW', key: 'w', label: 'য', shiftLabel: 'য়', finger: 'left-ring', hand: 'left', row: 'top' },
  KeyE: { code: 'KeyE', key: 'e', label: 'ড', shiftLabel: 'ঢ', finger: 'left-middle', hand: 'left', row: 'top' },
  KeyR: { code: 'KeyR', key: 'r', label: 'প', shiftLabel: 'ফ', finger: 'left-index', hand: 'left', row: 'top' },
  KeyT: { code: 'KeyT', key: 't', label: 'ট', shiftLabel: 'ঠ', finger: 'left-index', hand: 'left', row: 'top' },
  KeyY: { code: 'KeyY', key: 'y', label: 'চ', shiftLabel: 'ছ', finger: 'right-index', hand: 'right', row: 'top' },
  KeyU: { code: 'KeyU', key: 'u', label: 'জ', shiftLabel: 'ঝ', finger: 'right-index', hand: 'right', row: 'top' },
  KeyI: { code: 'KeyI', key: 'i', label: 'হ', shiftLabel: 'ঞ', finger: 'right-middle', hand: 'right', row: 'top' },
  KeyO: { code: 'KeyO', key: 'o', label: 'গ', shiftLabel: 'ঘ', finger: 'right-ring', hand: 'right', row: 'top' },
  KeyP: { code: 'KeyP', key: 'p', label: 'ড়', shiftLabel: 'ঢ়', finger: 'right-pinky', hand: 'right', row: 'top' },
  BracketLeft: { code: 'BracketLeft', key: '[', label: '[', shiftLabel: '{', finger: 'right-pinky', hand: 'right', row: 'top' },
  BracketRight: { code: 'BracketRight', key: ']', label: ']', shiftLabel: '}', finger: 'right-pinky', hand: 'right', row: 'top' },
  Backslash: { code: 'Backslash', key: '\\', label: 'ৎ', shiftLabel: '|', finger: 'right-pinky', hand: 'right', row: 'top' },

  // Home Row
  KeyA: { code: 'KeyA', key: 'a', label: 'ৃ', shiftLabel: 'র্', finger: 'left-pinky', hand: 'left', row: 'home' },
  KeyS: { code: 'KeyS', key: 's', label: 'ু', shiftLabel: 'ূ', finger: 'left-ring', hand: 'left', row: 'home' },
  KeyD: { code: 'KeyD', key: 'd', label: 'ি', shiftLabel: 'ী', finger: 'left-middle', hand: 'left', row: 'home' },
  KeyF: { code: 'KeyF', key: 'f', label: 'া', shiftLabel: 'অ', finger: 'left-index', hand: 'left', row: 'home' },
  KeyG: { code: 'KeyG', key: 'g', label: '্', shiftLabel: '।', finger: 'left-index', hand: 'left', row: 'home' },
  KeyH: { code: 'KeyH', key: 'h', label: 'ব', shiftLabel: 'ভ', finger: 'right-index', hand: 'right', row: 'home' },
  KeyJ: { code: 'KeyJ', key: 'j', label: 'ক', shiftLabel: 'খ', finger: 'right-index', hand: 'right', row: 'home' },
  KeyK: { code: 'KeyK', key: 'k', label: 'ত', shiftLabel: 'থ', finger: 'right-middle', hand: 'right', row: 'home' },
  KeyL: { code: 'KeyL', key: 'l', label: 'দ', shiftLabel: 'ধ', finger: 'right-ring', hand: 'right', row: 'home' },
  Semicolon: { code: 'Semicolon', key: ';', label: 'স', shiftLabel: 'শ', finger: 'right-pinky', hand: 'right', row: 'home' },
  Quote: { code: 'Quote', key: "'", label: "'", shiftLabel: '"', finger: 'right-pinky', hand: 'right', row: 'home' },

  // Bottom Row
  KeyZ: { code: 'KeyZ', key: 'z', label: '্র', shiftLabel: '্য', finger: 'left-pinky', hand: 'left', row: 'bottom' },
  KeyX: { code: 'KeyX', key: 'x', label: 'ও', shiftLabel: 'ৌ', finger: 'left-ring', hand: 'left', row: 'bottom' },
  KeyC: { code: 'KeyC', key: 'c', label: 'ে', shiftLabel: 'ৈ', finger: 'left-middle', hand: 'left', row: 'bottom' },
  KeyV: { code: 'KeyV', key: 'v', label: 'র', shiftLabel: 'ল', finger: 'left-index', hand: 'left', row: 'bottom' },
  KeyB: { code: 'KeyB', key: 'b', label: 'ন', shiftLabel: 'ণ', finger: 'left-index', hand: 'left', row: 'bottom' },
  KeyN: { code: 'KeyN', key: 'n', label: 'ষ', shiftLabel: 'ঃ', finger: 'right-index', hand: 'right', row: 'bottom' },
  KeyM: { code: 'KeyM', key: 'm', label: 'ম', shiftLabel: 'ঁ', finger: 'right-index', hand: 'right', row: 'bottom' },
  Comma: { code: 'Comma', key: ',', label: ',', shiftLabel: '<', finger: 'right-middle', hand: 'right', row: 'bottom' },
  Period: { code: 'Period', key: '.', label: '.', shiftLabel: '>', finger: 'right-ring', hand: 'right', row: 'bottom' },
  Slash: { code: 'Slash', key: '/', label: '/', shiftLabel: '?', finger: 'right-pinky', hand: 'right', row: 'bottom' },

  // Space
  Space: { code: 'Space', key: ' ', label: 'Space', finger: 'thumb', hand: 'right', row: 'space' }
};

// Character to Bijoy keystroke mapping
export const BIJOY_CHAR_TO_KEYSTROKES: Record<string, { key: string; shift: boolean }[]> = {
  // Independent Vowels (Swaroborno)
  'অ': [{ key: 'f', shift: true }],
  'আ': [{ key: 'g', shift: false }, { key: 'f', shift: false }],
  'ই': [{ key: 'g', shift: false }, { key: 'd', shift: false }],
  'ঈ': [{ key: 'g', shift: false }, { key: 'd', shift: true }],
  'উ': [{ key: 'g', shift: false }, { key: 's', shift: false }],
  'ঊ': [{ key: 'g', shift: false }, { key: 's', shift: true }],
  'ঋ': [{ key: 'g', shift: false }, { key: 'a', shift: false }],
  'এ': [{ key: 'g', shift: false }, { key: 'c', shift: false }],
  'ঐ': [{ key: 'g', shift: false }, { key: 'c', shift: true }],
  'ও': [{ key: 'x', shift: false }],
  'ঔ': [{ key: 'g', shift: false }, { key: 'x', shift: true }],

  // Kar (Vowel Diacritics)
  'া': [{ key: 'f', shift: false }],
  'ি': [{ key: 'd', shift: false }],
  'ী': [{ key: 'd', shift: true }],
  'ু': [{ key: 's', shift: false }],
  'ূ': [{ key: 's', shift: true }],
  'ৃ': [{ key: 'a', shift: false }],
  'ে': [{ key: 'c', shift: false }],
  'ৈ': [{ key: 'c', shift: true }],
  'ো': [{ key: 'c', shift: false }, { key: 'f', shift: false }],
  'ৌ': [{ key: 'x', shift: true }],

  // Consonants (Byanjonborno)
  'ক': [{ key: 'j', shift: false }],
  'খ': [{ key: 'j', shift: true }],
  'গ': [{ key: 'o', shift: false }],
  'ঘ': [{ key: 'o', shift: true }],
  'ঙ': [{ key: 'q', shift: false }],
  'চ': [{ key: 'y', shift: false }],
  'ছ': [{ key: 'y', shift: true }],
  'জ': [{ key: 'u', shift: false }],
  'ঝ': [{ key: 'u', shift: true }],
  'ঞ': [{ key: 'i', shift: true }],
  'ট': [{ key: 't', shift: false }],
  'ঠ': [{ key: 't', shift: true }],
  'ড': [{ key: 'e', shift: false }],
  'ঢ': [{ key: 'e', shift: true }],
  'ণ': [{ key: 'b', shift: true }],
  'ত': [{ key: 'k', shift: false }],
  'থ': [{ key: 'k', shift: true }],
  'দ': [{ key: 'l', shift: false }],
  'ধ': [{ key: 'l', shift: true }],
  'ন': [{ key: 'b', shift: false }],
  'প': [{ key: 'r', shift: false }],
  'ফ': [{ key: 'r', shift: true }],
  'ব': [{ key: 'h', shift: false }],
  'ভ': [{ key: 'h', shift: true }],
  'ম': [{ key: 'm', shift: false }],
  'য': [{ key: 'w', shift: false }],
  'র': [{ key: 'v', shift: false }],
  'ল': [{ key: 'v', shift: true }],
  'শ': [{ key: ';', shift: true }],
  'ষ': [{ key: 'n', shift: false }],
  'স': [{ key: ';', shift: false }],
  'হ': [{ key: 'i', shift: false }],
  'ড়': [{ key: 'p', shift: false }],
  'ঢ়': [{ key: 'p', shift: true }],
  'য়': [{ key: 'w', shift: true }],
  'য়': [{ key: 'w', shift: true }],
  'ৎ': [{ key: '\\', shift: false }], // Backslash in Bijoy 52
  'ং': [{ key: 'q', shift: true }],
  'ঃ': [{ key: 'n', shift: true }],
  'ঁ': [{ key: 'm', shift: true }],

  // Special Linkers, Virama & Nukta
  '্': [{ key: 'g', shift: false }], // Hasant/Virama -> key G, Left Index
  '়': [{ key: 'p', shift: false }], // Nukta fallback -> key P, Right Pinky
  '।': [{ key: 'g', shift: true }],  // Dari -> Shift + G, Left Index
  '॥': [{ key: 'g', shift: true }, { key: 'g', shift: true }],
  '৳': [{ key: '4', shift: true }],  // Taka -> Shift + 4, Left Index
  '্র': [{ key: 'z', shift: false }],
  '্য': [{ key: 'z', shift: true }],
  'র্': [{ key: 'a', shift: true }],

  // Numbers
  '০': [{ key: '0', shift: false }],
  '১': [{ key: '1', shift: false }],
  '২': [{ key: '2', shift: false }],
  '৩': [{ key: '3', shift: false }],
  '৪': [{ key: '4', shift: false }],
  '৫': [{ key: '5', shift: false }],
  '৬': [{ key: '6', shift: false }],
  '৭': [{ key: '7', shift: false }],
  '৮': [{ key: '8', shift: false }],
  '৯': [{ key: '9', shift: false }],

  // Punctuations
  ' ': [{ key: ' ', shift: false }],
  ',': [{ key: ',', shift: false }],
  '.': [{ key: '.', shift: false }],
  '?': [{ key: '/', shift: true }],
  '!': [{ key: '1', shift: true }],
  ';': [{ key: ';', shift: false }],
  ':': [{ key: ';', shift: true }],
  '-': [{ key: '-', shift: false }],
  '_': [{ key: '-', shift: true }],
  '(': [{ key: '9', shift: true }],
  ')': [{ key: '0', shift: true }],
  '[': [{ key: '[', shift: false }],
  ']': [{ key: ']', shift: false }],
  '{': [{ key: '[', shift: true }],
  '}': [{ key: ']', shift: true }],
  '/': [{ key: '/', shift: false }],
  '\\': [{ key: '\\', shift: false }],
  '"': [{ key: "'", shift: true }],
  "'": [{ key: "'", shift: false }],
  '=': [{ key: '=', shift: false }],
  '+': [{ key: '=', shift: true }],
  '%': [{ key: '5', shift: true }],
  '@': [{ key: '2', shift: true }],
  '#': [{ key: '3', shift: true }],
  '$': [{ key: '4', shift: true }],
  '^': [{ key: '6', shift: true }],
  '&': [{ key: '7', shift: true }],
  '*': [{ key: '8', shift: true }],
  '`': [{ key: '`', shift: false }],
  '~': [{ key: '`', shift: true }],

  // Common Conjuncts (Pre-calculated Bijoy key sequences)
  'ক্ষ': [{ key: 'j', shift: false }, { key: 'g', shift: false }, { key: 'n', shift: false }],
  'জ্ঞ': [{ key: 'u', shift: false }, { key: 'g', shift: false }, { key: 'i', shift: true }],
  'ক্ত': [{ key: 'j', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: false }],
  'ক্র': [{ key: 'j', shift: false }, { key: 'z', shift: false }],
  'ক্ল': [{ key: 'j', shift: false }, { key: 'g', shift: false }, { key: 'v', shift: true }],
  'ঙ্ক': [{ key: 'q', shift: false }, { key: 'g', shift: false }, { key: 'j', shift: false }],
  'ঙ্গ': [{ key: 'q', shift: false }, { key: 'g', shift: false }, { key: 'o', shift: false }],
  'চ্চ': [{ key: 'y', shift: false }, { key: 'g', shift: false }, { key: 'y', shift: false }],
  'চ্ছ': [{ key: 'y', shift: false }, { key: 'g', shift: false }, { key: 'y', shift: true }],
  'ঞ্চ': [{ key: 'i', shift: true }, { key: 'g', shift: false }, { key: 'y', shift: false }],
  'ঞ্জ': [{ key: 'i', shift: true }, { key: 'g', shift: false }, { key: 'u', shift: false }],
  'ট্ট': [{ key: 't', shift: false }, { key: 'g', shift: false }, { key: 't', shift: false }],
  'ট্র': [{ key: 't', shift: false }, { key: 'z', shift: false }],
  'ণ্ট': [{ key: 'b', shift: true }, { key: 'g', shift: false }, { key: 't', shift: false }],
  'ণ্ড': [{ key: 'b', shift: true }, { key: 'g', shift: false }, { key: 'e', shift: false }],
  'ত্ত': [{ key: 'k', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: false }],
  'ত্র': [{ key: 'k', shift: false }, { key: 'z', shift: false }],
  'ত্ব': [{ key: 'k', shift: false }, { key: 'g', shift: false }, { key: 'h', shift: false }],
  'দ্দ': [{ key: 'l', shift: false }, { key: 'g', shift: false }, { key: 'l', shift: false }],
  'দ্ধ': [{ key: 'l', shift: false }, { key: 'g', shift: false }, { key: 'l', shift: true }],
  'দ্ব': [{ key: 'l', shift: false }, { key: 'g', shift: false }, { key: 'h', shift: false }],
  'দ্ম': [{ key: 'l', shift: false }, { key: 'g', shift: false }, { key: 'm', shift: false }],
  'দ্র': [{ key: 'l', shift: false }, { key: 'z', shift: false }],
  'ন্ট': [{ key: 'b', shift: false }, { key: 'g', shift: false }, { key: 't', shift: false }],
  'ন্ত': [{ key: 'b', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: false }],
  'ন্থ': [{ key: 'b', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: true }],
  'ন্দ': [{ key: 'b', shift: false }, { key: 'g', shift: false }, { key: 'l', shift: false }],
  'ন্ধ': [{ key: 'b', shift: false }, { key: 'g', shift: false }, { key: 'l', shift: true }],
  'ন্ন': [{ key: 'b', shift: false }, { key: 'g', shift: false }, { key: 'b', shift: false }],
  'ন্ম': [{ key: 'b', shift: false }, { key: 'g', shift: false }, { key: 'm', shift: false }],
  'প্ত': [{ key: 'r', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: false }],
  'প্ল': [{ key: 'r', shift: false }, { key: 'g', shift: false }, { key: 'v', shift: true }],
  'প্র': [{ key: 'r', shift: false }, { key: 'z', shift: false }],
  'ম্প': [{ key: 'm', shift: false }, { key: 'g', shift: false }, { key: 'r', shift: false }],
  'ম্ব': [{ key: 'm', shift: false }, { key: 'g', shift: false }, { key: 'h', shift: false }],
  'ম্ভ': [{ key: 'm', shift: false }, { key: 'g', shift: false }, { key: 'h', shift: true }],
  'ম্ম': [{ key: 'm', shift: false }, { key: 'g', shift: false }, { key: 'm', shift: false }],
  'ল্ল': [{ key: 'v', shift: true }, { key: 'g', shift: false }, { key: 'v', shift: true }],
  'শ্চ': [{ key: ';', shift: true }, { key: 'g', shift: false }, { key: 'y', shift: false }],
  'শ্র': [{ key: ';', shift: true }, { key: 'z', shift: false }],
  'শ্ব': [{ key: ';', shift: true }, { key: 'g', shift: false }, { key: 'h', shift: false }],
  'ষ্ট': [{ key: 'n', shift: false }, { key: 'g', shift: false }, { key: 't', shift: false }],
  'ষ্ঠ': [{ key: 'n', shift: false }, { key: 'g', shift: false }, { key: 't', shift: true }],
  'ষ্ণ': [{ key: 'n', shift: false }, { key: 'g', shift: false }, { key: 'b', shift: true }],
  'ষ্প': [{ key: 'n', shift: false }, { key: 'g', shift: false }, { key: 'r', shift: false }],
  'স্ত': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: false }],
  'স্থ': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'k', shift: true }],
  'স্ন': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'b', shift: false }],
  'স্প': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'r', shift: false }],
  'স্ফ': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'r', shift: true }],
  'স্ব': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'h', shift: false }],
  'স্ম': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'm', shift: false }],
  'স্র': [{ key: ';', shift: false }, { key: 'z', shift: false }],
  'স্ল': [{ key: ';', shift: false }, { key: 'g', shift: false }, { key: 'v', shift: true }],
  'হ্ন': [{ key: 'i', shift: false }, { key: 'g', shift: false }, { key: 'b', shift: false }],
  'হ্ণ': [{ key: 'i', shift: false }, { key: 'g', shift: false }, { key: 'b', shift: true }],
  'হ্ম': [{ key: 'i', shift: false }, { key: 'g', shift: false }, { key: 'm', shift: false }],
  'হ্ল': [{ key: 'i', shift: false }, { key: 'g', shift: false }, { key: 'v', shift: true }],
  'হ্র': [{ key: 'i', shift: false }, { key: 'z', shift: false }]
};
