import { KeyMapEntry } from '../../types';

// Complete standard Bijoy 52 Unicode Keymap
export const BIJOY_KEYMAP: Record<string, KeyMapEntry> = {
  // Number Row
  Backquote: { code: 'Backquote', key: '`', label: '`', shiftLabel: '~', finger: 'left-pinky', hand: 'left', row: 'number' },
  Digit1: { code: 'Digit1', key: '1', label: '১', shiftLabel: '!', finger: 'left-pinky', hand: 'left', row: 'number' },
  Digit2: { code: 'Digit2', key: '2', label: '২', shiftLabel: '@', finger: 'left-ring', hand: 'left', row: 'number' },
  Digit3: { code: 'Digit3', key: '3', label: '৩', shiftLabel: '#', finger: 'left-middle', hand: 'left', row: 'number' },
  Digit4: { code: 'Digit4', key: '4', label: '৪', shiftLabel: '$', finger: 'left-index', hand: 'left', row: 'number' },
  Digit5: { code: 'Digit5', key: '5', label: '৫', shiftLabel: '%', finger: 'left-index', hand: 'left', row: 'number' },
  Digit6: { code: 'Digit6', key: '6', label: '৬', shiftLabel: '^', finger: 'right-index', hand: 'right', row: 'number' },
  Digit7: { code: 'Digit7', key: '7', label: '৭', shiftLabel: '&', finger: 'right-index', hand: 'right', row: 'number' },
  Digit8: { code: 'Digit8', key: '8', label: '৮', shiftLabel: '*', finger: 'right-middle', hand: 'right', row: 'number' },
  Digit9: { code: 'Digit9', key: '9', label: '৯', shiftLabel: '(', finger: 'right-ring', hand: 'right', row: 'number' },
  Digit0: { code: 'Digit0', key: '0', label: '০', shiftLabel: ')', finger: 'right-pinky', hand: 'right', row: 'number' },
  Minus: { code: 'Minus', key: '-', label: '-', shiftLabel: '_', finger: 'right-pinky', hand: 'right', row: 'number' },
  Equal: { code: 'Equal', key: '=', label: '=', shiftLabel: '+', finger: 'right-pinky', hand: 'right', row: 'number' },

  // Top Row
  KeyQ: { code: 'KeyQ', key: 'q', label: 'ঙ', shiftLabel: 'ং', finger: 'left-pinky', hand: 'left', row: 'top' },
  KeyW: { code: 'KeyW', key: 'w', label: 'য', shiftLabel: 'য়', finger: 'left-ring', hand: 'left', row: 'top' },
  KeyE: { code: 'KeyE', key: 'e', label: 'ড', shiftLabel: 'ঢ', finger: 'left-middle', hand: 'left', row: 'top' },
  KeyR: { code: 'KeyR', key: 'r', label: 'প', shiftLabel: 'ফ', finger: 'left-index', hand: 'left', row: 'top' },
  KeyT: { code: 'KeyT', key: 't', label: 'ট', shiftLabel: 'ঠ', finger: 'left-index', hand: 'left', row: 'top' },
  KeyY: { code: 'KeyY', key: 'y', label: 'চ', shiftLabel: 'ছ', finger: 'right-index', hand: 'right', row: 'top' },
  KeyU: { code: 'KeyU', key: 'u', label: 'জ', shiftLabel: 'ঝ', finger: 'right-index', hand: 'right', row: 'top' },
  KeyI: { code: 'KeyI', key: 'i', label: 'হ', shiftLabel: 'ঞ', finger: 'right-middle', hand: 'right', row: 'top' },
  KeyO: { code: 'KeyO', key: 'o', label: 'গ', shiftLabel: 'ঘ', finger: 'right-ring', hand: 'right', row: 'top' },
  KeyP: { code: 'KeyP', key: 'p', label: 'ড়', shiftLabel: 'ঢ়', finger: 'right-pinky', hand: 'right', row: 'top' },
  BracketLeft: { code: 'BracketLeft', key: '[', label: '[', shiftLabel: '{', finger: 'right-pinky', hand: 'right', row: 'top' },
  BracketRight: { code: 'BracketRight', key: ']', label: ']', shiftLabel: '}', finger: 'right-pinky', hand: 'right', row: 'top' },

  // Home Row
  KeyA: { code: 'KeyA', key: 'a', label: 'ৃ', shiftLabel: 'র্', finger: 'left-pinky', hand: 'left', row: 'home' },
  KeyS: { code: 'KeyS', key: 's', label: 'ু', shiftLabel: 'ূ', finger: 'left-ring', hand: 'left', row: 'home' },
  KeyD: { code: 'KeyD', key: 'd', label: 'ি', shiftLabel: 'ী', finger: 'left-middle', hand: 'left', row: 'home' },
  KeyF: { code: 'KeyF', key: 'f', label: 'া', shiftLabel: 'অ', finger: 'left-index', hand: 'left', row: 'home' },
  KeyG: { code: 'KeyG', key: 'g', label: '্', shiftLabel: '।', finger: 'left-index', hand: 'left', row: 'home' },
  KeyH: { code: 'KeyH', key: 'h', label: 'ব', shiftLabel: 'ভ', finger: 'right-index', hand: 'right', row: 'home' },
  KeyJ: { code: 'KeyJ', key: 'j', label: 'ক', shiftLabel: 'খ', finger: 'right-index', hand: 'right', row: 'home' },
  KeyK: { code: 'KeyK', key: 'k', label: 'ত', shiftLabel: 'থ', finger: 'right-middle', hand: 'right', row: 'home' },
  KeyL: { code: 'KeyL', key: 'l', label: 'দ', shiftLabel: 'ধ', finger: 'right-ring', hand: 'right', row: 'home' },
  Semicolon: { code: 'Semicolon', key: ';', label: 'স', shiftLabel: 'শ', finger: 'right-pinky', hand: 'right', row: 'home' },
  Quote: { code: 'Quote', key: "'", label: "'", shiftLabel: '"', finger: 'right-pinky', hand: 'right', row: 'home' },

  // Bottom Row
  KeyZ: { code: 'KeyZ', key: 'z', label: '্র', shiftLabel: '্য', finger: 'left-pinky', hand: 'left', row: 'bottom' },
  KeyX: { code: 'KeyX', key: 'x', label: 'ও', shiftLabel: 'ৌ', finger: 'left-ring', hand: 'left', row: 'bottom' },
  KeyC: { code: 'KeyC', key: 'c', label: 'ে', shiftLabel: 'ৈ', finger: 'left-middle', hand: 'left', row: 'bottom' },
  KeyV: { code: 'KeyV', key: 'v', label: 'র', shiftLabel: 'ল', finger: 'left-index', hand: 'left', row: 'bottom' },
  KeyB: { code: 'KeyB', key: 'b', label: 'ন', shiftLabel: 'ণ', finger: 'left-index', hand: 'left', row: 'bottom' },
  KeyN: { code: 'KeyN', key: 'n', label: 'ষ', shiftLabel: 'ঃ', finger: 'right-index', hand: 'right', row: 'bottom' },
  KeyM: { code: 'KeyM', key: 'm', label: 'ম', shiftLabel: 'ঁ', finger: 'right-index', hand: 'right', row: 'bottom' },
  Comma: { code: 'Comma', key: ',', label: ',', shiftLabel: '<', finger: 'right-middle', hand: 'right', row: 'bottom' },
  Period: { code: 'Period', key: '.', label: '.', shiftLabel: '>', finger: 'right-ring', hand: 'right', row: 'bottom' },
  Slash: { code: 'Slash', key: '/', label: '/', shiftLabel: '?', finger: 'right-pinky', hand: 'right', row: 'bottom' },

  // Space
  Space: { code: 'Space', key: ' ', label: 'Space', finger: 'thumb', hand: 'right', row: 'space' }
};

// Character to Bijoy keystroke mapping
export const BIJOY_CHAR_TO_KEYSTROKES: Record<string, { key: string; shift: boolean }[]> = {
  // Independent Vowels
  'অ': [{ key: 'f', shift: true }],
  'আ': [{ key: 'g', shift: false }, { key: 'f', shift: false }],
  'ই': [{ key: 'g', shift: false }, { key: 'd', shift: false }],
  'ঈ': [{ key: 'g', shift: false }, { key: 'd', shift: true }],
  'উ': [{ key: 'g', shift: false }, { key: 's', shift: false }],
  'ঊ': [{ key: 'g', shift: false }, { key: 's', shift: true }],
  'ঋ': [{ key: 'g', shift: false }, { key: 'a', shift: false }],
  'এ': [{ key: 'g', shift: false }, { key: 'c', shift: false }],
  'ঐ': [{ key: 'g', shift: false }, { key: 'c', shift: true }],
  'ও': [{ key: 'x', shift: false }],
  'ঔ': [{ key: 'g', shift: false }, { key: 'x', shift: true }],

  // Kar (Vowel Diacritics)
  'া': [{ key: 'f', shift: false }],
  'ি': [{ key: 'd', shift: false }],
  'ী': [{ key: 'd', shift: true }],
  'ু': [{ key: 's', shift: false }],
  'ূ': [{ key: 's', shift: true }],
  'ৃ': [{ key: 'a', shift: false }],
  'ে': [{ key: 'c', shift: false }],
  'ৈ': [{ key: 'c', shift: true }],
  'ো': [{ key: 'c', shift: false }, { key: 'f', shift: false }],
  'ৌ': [{ key: 'x', shift: true }],

  // Consonants
  'ক': [{ key: 'j', shift: false }],
  'খ': [{ key: 'j', shift: true }],
  'গ': [{ key: 'o', shift: false }],
  'ঘ': [{ key: 'o', shift: true }],
  'ঙ': [{ key: 'q', shift: false }],
  'চ': [{ key: 'y', shift: false }],
  'ছ': [{ key: 'y', shift: true }],
  'জ': [{ key: 'u', shift: false }],
  'ঝ': [{ key: 'u', shift: true }],
  'ঞ': [{ key: 'i', shift: true }],
  'ট': [{ key: 't', shift: false }],
  'ঠ': [{ key: 't', shift: true }],
  'ড': [{ key: 'e', shift: false }],
  'ঢ': [{ key: 'e', shift: true }],
  'ণ': [{ key: 'b', shift: true }],
  'ত': [{ key: 'k', shift: false }],
  'থ': [{ key: 'k', shift: true }],
  'দ': [{ key: 'l', shift: false }],
  'ধ': [{ key: 'l', shift: true }],
  'ন': [{ key: 'b', shift: false }],
  'প': [{ key: 'r', shift: false }],
  'ফ': [{ key: 'r', shift: true }],
  'ব': [{ key: 'h', shift: false }],
  'ভ': [{ key: 'h', shift: true }],
  'ম': [{ key: 'm', shift: false }],
  'য': [{ key: 'w', shift: false }],
  'র': [{ key: 'v', shift: false }],
  'ল': [{ key: 'v', shift: true }],
  'শ': [{ key: ';', shift: true }],
  'ষ': [{ key: 'n', shift: false }],
  'স': [{ key: ';', shift: false }],
  'হ': [{ key: 'i', shift: false }],
  'ড়': [{ key: 'p', shift: false }],
  'ঢ়': [{ key: 'p', shift: true }],
  'য়': [{ key: 'w', shift: true }],
  'ৎ': [{ key: 'g', shift: false }, { key: 'k', shift: true }],
  'ং': [{ key: 'q', shift: true }],
  'ঃ': [{ key: 'n', shift: true }],
  'ঁ': [{ key: 'm', shift: true }],
  '্': [{ key: 'g', shift: false }],
  '।': [{ key: 'g', shift: true }],
  '্র': [{ key: 'z', shift: false }],
  '্য': [{ key: 'z', shift: true }],
  'র্': [{ key: 'a', shift: true }],
  ',': [{ key: ',', shift: false }],
  '.': [{ key: '.', shift: false }],
  '?': [{ key: '/', shift: true }],
  '!': [{ key: '1', shift: true }],
  ';': [{ key: ';', shift: false }],
  ':': [{ key: ';', shift: true }],
  '-': [{ key: '-', shift: false }],
  '০': [{ key: '0', shift: false }],
  '১': [{ key: '1', shift: false }],
  '২': [{ key: '2', shift: false }],
  '৩': [{ key: '3', shift: false }],
  '৪': [{ key: '4', shift: false }],
  '৫': [{ key: '5', shift: false }],
  '৬': [{ key: '6', shift: false }],
  '৭': [{ key: '7', shift: false }],
  '৮': [{ key: '8', shift: false }],
  '৯': [{ key: '9', shift: false }],
  ' ': [{ key: ' ', shift: false }]
};
